name: source_gen_cli
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: Rodsevich <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'
  #TODO: back to normal when Pull Request approved

dependencies:
  resource: '>=2.1.2 <3.0.0'
  args: 'any'
  dart_config: 'any'
  console: '>=2.2.4 <3.0.0'
  # mustache4dart: #'>= 1.0.0 < 2.0.0'
  #   git: git://github.com/Rodsevich/mustache4dart
    # url: https://github.com/Rodsevich/mustache4dart
  source_gen:
    path: /home/nico/src/source_gen
    # git: git://github.com/Rodsevich/source_gen
      # url: https://github.com/Rodsevich/source_gen

#dependencies:
#  lib_name: any

  path: '>=1.4.1 <2.0.0'
  den_api: # '>=0.1.0 <0.2.0'
    path: /home/nico/src/den_api
  pub_semver: '>=1.3.2 <2.0.0'
  logging: '>=0.11.3+1 <0.12.0'
  mustache: '>=0.2.5+1 <0.3.0'
  diff: '>=0.1.1 <0.2.0'
  analyzer: '>=0.29.10 <0.30.0'
  code_transformers: '>=0.5.1 <0.6.0'
  barback: '>=0.15.2+10 <0.16.0'
  resolver: '>=0.1.1 <0.2.0'
  annotationscanner: '>=0.0.1 <0.1.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  build_runner: '>=0.3.0+1 <0.4.0'
